import assert from 'node:assert/strict';
import { createMessageQueue } from '../src/core/message-queue.js';
const tick = () => new Promise(resolve => setImmediate(resolve));
const queue = createMessageQueue();
const seen = [];
let finish;
queue.submit('one', () => new Promise(resolve => { finish = resolve; seen.push('first'); }));
queue.submit('one', async () => { seen.push('second'); }, { queue: true });
assert.throws(() => queue.submit('one', () => {}), /already running/);
assert.throws(() => queue.submit('one', () => {}, { queue: true }), /already has a queued/);
queue.submit('other', async () => { seen.push('other'); });
await tick();
assert.deepEqual(seen, ['first', 'other']);
finish(); await tick();
assert.deepEqual(seen, ['first', 'other', 'second']);
assert.equal(queue.busy('one'), false);
queue.submit('one', () => new Promise(resolve => { finish = resolve; }));
queue.submit('one', async () => { seen.push('cancelled'); }, { queue: true });
queue.cancel('one'); finish(); await tick();
assert.ok(!seen.includes('cancelled'));
let error;
queue.submit('one', async () => { throw Error('failure'); }, { onError: e => { error = e.message; } });
queue.submit('one', async () => { seen.push('after failure'); }, { queue: true });
await tick();
assert.equal(error, 'failure');
assert.equal(seen.at(-1), 'after failure');
assert.equal(queue.busy('one'), false);
console.log('PASS per-tab follow-ups serialize, reject overflow, run independently, cancel and recover from failure');
