import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import { createNetworkGate } from '../src/core/network-gate.js';
let connected = false, time = 0, calls = 0;
const gate = createNetworkGate(async () => { calls++; return { connected }; }, { now: () => time });
const results = await Promise.all([gate(), gate()]);
assert.equal(calls, 1);
assert.match(results[0].error, /Turn on Tailscale/);
connected = true;
assert.equal((await gate()).connected, false);
time = 3000;
assert.equal((await gate()).connected, true);
connected = false; time = 6000;
assert.equal((await gate()).connected, false);
assert.equal((await createNetworkGate(async () => { throw Error('missing client'); })()).connected, false);
const source = await fs.readFile('server/public/app.js', 'utf8');
const nodes = Object.fromEntries(['network-gate', 'network-gate-title', 'network-gate-message', 'bar'].map(id => [id, { id }]));
let initialized = 0;
const context = { $: id => nodes[id], api: async () => ({ connected }), initializeApp: async () => { initialized++; },
  document: { body: { children: Object.values(nodes) } }, window: { addEventListener() {} }, setInterval() {} };
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('let networkChecking = false;')).replace(/checkNetworkConnection\(\);\s*$/, ''), context);
await context.checkNetworkConnection();
assert.equal(nodes['network-gate'].hidden, false);
assert.equal(nodes.bar.inert, true);
connected = true;
await context.checkNetworkConnection();
assert.equal(nodes['network-gate'].hidden, true);
assert.equal(nodes.bar.inert, false);
assert.equal(initialized, 1);
await context.checkNetworkConnection();
assert.equal(initialized, 1);
connected = false;
await context.checkNetworkConnection();
assert.equal(nodes['network-gate'].hidden, false);
console.log('PASS network gate blocks, deduplicates probes, fails closed and restores UI automatically');
