import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
const source = await fs.readFile('server/public/app.js', 'utf8');
const html = await fs.readFile('server/public/index.html', 'utf8');
const nodes = new Map();
const $ = (id) => { if (!nodes.has(id)) nodes.set(id, {}); return nodes.get(id); };
let rendered;
const context = { $, openSheet: (html) => { rendered = html; }, closeSheet() {},
  githubSheet() {}, machinesSheet() {}, networkSheet() {}, filesSheet() {}, modelsSheet() {}, notifySheet() {}, emailSheet() {}, window: {} };
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('async function settingsSheet()'), source.indexOf('async function sessionSettingsSheet()')), context);
await context.settingsSheet();
assert.match(rendered, /Distributed Orchestrator settings/);
assert.match(rendered, /AI sources/);
assert.doesNotMatch(rendered, /s-models|s-dir|s-name|id="h-git"/);
assert.equal(typeof $('h-machines').onclick, 'function');
assert.doesNotMatch(html, /id="tabs"|data-tab|id="panel"|mon-chat-toggle/);
Object.assign(context, { state: { session: { name: 'My session', model: 'model', projectDir: '/project', appId: 'app' }, apps: [{ id: 'app', name: 'My app' }], models: { model: { label: 'My model', hasKey: true } } }, cur: () => ({ session: {} }), idlePlaceholder: () => '', showBanner() {} });
vm.runInContext(source.slice(source.indexOf('function paintHeader()'), source.indexOf('function showBanner(')), context);
context.paintHeader();
assert.equal(nodes.has('title-app'), false);
assert.doesNotMatch(html, /id="title-app"/);
assert.equal($('title-name').textContent, 'My app');
assert.equal($('title-sub').textContent, 'Model: My model');
assert.equal(nodes.has('title-dir'), false);
assert.doesNotMatch(html, /id="title-dir"/);
assert.doesNotMatch(source.slice(source.indexOf('async function openSession('), source.indexOf('function projectSession(')), /meta\.projectDir/);
assert.match(source, /id="s-dir" value="\$\{esc\(session\.projectDir\)\}"/);
context.state.session = null;
context.paintHeader();
assert.equal($('title-name').textContent, 'Distributed Orchestrator');
assert.doesNotMatch(source.slice(source.indexOf('async function openSession('), source.indexOf('function projectSession(')), /textContent = meta.name/);
console.log('PASS compact app header without duplicate session title; directory stays in Edit session');
