import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'orchestrator bootstrap '));
let blocker;
try {
  for (const folder of ['scripts', 'src/core', 'server', '.launcher', 'node_modules/cross-spawn']) await fs.mkdir(path.join(dir, folder), { recursive: true });
  await fs.copyFile('scripts/startup-update.mjs', path.join(dir, 'scripts/startup-update.mjs'));
  await fs.copyFile('scripts/restart-server.mjs', path.join(dir, 'scripts/restart-server.mjs'));
  await fs.copyFile('scripts/start.mjs', path.join(dir, 'scripts/start.mjs'));
  await fs.copyFile('scripts/stop-server.mjs', path.join(dir, 'scripts/stop-server.mjs'));
  await fs.copyFile('src/core/platform.js', path.join(dir, 'src/core/platform.js'));
  await fs.writeFile(path.join(dir, 'package.json'), '{"type":"module"}');
  await fs.writeFile(path.join(dir, 'package-lock.json'), '{}');
  await fs.writeFile(path.join(dir, 'node_modules/cross-spawn/package.json'), '{}');
  await fs.writeFile(path.join(dir, '.launcher/dependencies.sha256'), crypto.createHash('sha256').update('{}').digest('hex'));
  await fs.writeFile(path.join(dir, 'server/index.js'), `import http from 'node:http';
    const server = http.createServer((req, res) => { res.end('ok'); setTimeout(() => server.close(), 100); });
    server.listen(Number(process.env.HARNESS_PORT), '127.0.0.1'); setTimeout(() => process.exit(0), 2000);`);
  blocker = net.createServer((socket) => socket.destroy());
  await new Promise(r => blocker.listen(0, '127.0.0.1', r));
  const port = blocker.address().port;
  await new Promise(r => blocker.close(r));
  const env = { ...process.env, HARNESS_PORT: String(port), HARNESS_DATA_DIR: path.join(dir, 'data'), HARNESS_TOKEN: 'test-only-token' };
  const run = () => promisify(execFile)(process.execPath, [path.join(dir, 'scripts/start.mjs'), '--no-browser'], { env, timeout: 10000 });
  assert.match((await run()).stdout, /Join an existing system/);
  const config = await fs.readFile(path.join(dir, '.orchestrator-node.env'), 'utf8');
  await run();
  assert.equal(await fs.readFile(path.join(dir, '.orchestrator-node.env'), 'utf8'), config);
  // A second computer publishes while this installation is stopped.
  const git = async (cwd, ...args) => promisify(execFile)('git', ['-c', 'user.name=test', '-c', 'user.email=test@localhost', ...args], { cwd });
  const remote = path.join(dir, 'remote.git'), other = path.join(dir, 'other');
  await fs.writeFile(path.join(dir, '.gitignore'), 'node_modules/\n.launcher/\n.orchestrator-node.env\nremote.git/\nother/\ndata/\n');
  await git(dir, 'init', '-b', 'main');
  await git(dir, 'add', '.'); await git(dir, 'commit', '-m', 'initial');
  await git(dir, 'init', '--bare', remote);
  await git(dir, 'remote', 'add', 'origin', remote); await git(dir, 'push', '-u', 'origin', 'main');
  await git(dir, 'clone', '-b', 'main', remote, other);
  await fs.appendFile(path.join(other, 'server/index.js'), "\nconsole.log('STARTED UPDATED SERVER');\n");
  await git(other, 'commit', '-am', 'update from another computer'); await git(other, 'push');
  const updated = await run();
  assert.match(updated.stdout, /Startup update verified:/);
  assert.match(updated.stdout, /STARTED UPDATED SERVER/);
  assert.ok(updated.stdout.indexOf('Startup update verified:') < updated.stdout.indexOf('STARTED UPDATED SERVER'));
  await fs.appendFile(path.join(other, 'server/index.js'), "\nconsole.log('RESTART PULLED UPDATE');\n");
  await git(other, 'commit', '-am', 'update before restart'); await git(other, 'push');
  const restart = () => promisify(execFile)(process.execPath,
    [path.join(dir, 'scripts/restart-server.mjs'), String(port), path.join(dir, 'server/index.js')],
    { env, timeout: 10000 });
  const restarted = await restart();
  assert.match(restarted.stdout, /RESTART PULLED UPDATE/);
  assert.ok(restarted.stdout.indexOf('Startup update verified:') < restarted.stdout.indexOf('RESTART PULLED UPDATE'));
  await fs.appendFile(path.join(dir, 'server/index.js'), '\n// local edit\n');
  await assert.rejects(run(), /Local changes/);
  await assert.rejects(restart(), /Local changes/);
  await git(dir, 'restore', 'server/index.js');
  await git(dir, 'remote', 'set-url', 'origin', path.join(dir, 'missing.git'));
  await assert.rejects(run(), /update check failed/);
  await assert.rejects(restart(), /update check failed/);
  await git(dir, 'remote', 'set-url', 'origin', remote);
  await new Promise(r => blocker.listen(port, '0.0.0.0', r));
  await assert.rejects(run(), /already in use/);
  assert.equal(blocker.listening, true);
  console.log('PASS first-run server startup, checkout paths with spaces, config preservation and occupied-port refusal');
} finally {
  if (blocker?.listening) await new Promise(r => blocker.close(r));
  await fs.rm(dir, { recursive: true, force: true });
}
