import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
const source = await fs.readFile('server/public/app.js', 'utf8');
const context = { esc: String, render: String, compact: String, clock: () => '', copyTexts: new Map(), toolBlock: () => '<tool>tool</tool>' };
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function activityChip('), source.indexOf('function drawTranscript(')), context);
const turn = { user: { id: 'u', text: 'QUESTION' }, texts: [{ text: 'PROGRESS', model: 'm' }, { text: 'FINAL', model: 'm' }], steps: [{ call: { name: 'shell' }, result: { ok: true } }], notes: [], files: [], endedOn: 'reply' };
const html = context.turnHtml(turn, 0, false, 1, true);
assert.ok(html.indexOf('QUESTION') < html.indexOf('Progress ·'));
assert.match(html, /id="fold-u" hidden/);
assert.ok(html.indexOf('PROGRESS') < html.indexOf('final-reply'));
assert.match(html, /id="fold-u-final"><div class="body">FINAL/);
assert.match(html, /data-fold="u-input"/);
assert.ok(html.indexOf('data-fold="u-final"') < html.indexOf('>FINAL'));
vm.runInContext("closedFolds.add('u-final'); closedFolds.add('u-input');", context);
assert.match(context.turnHtml(turn, 0, false, 1, true), /id="fold-u-final" hidden/);
assert.match(context.turnHtml(turn, 0, false, 1, true), /id="fold-u-input" hidden/);
assert.doesNotMatch(context.turnHtml(turn, 0, true, 1, true), /final-reply|working · shell/);
assert.doesNotMatch(context.turnHtml({ ...turn, endedOn: 'tool' }, 0, false, 1, true), /final-reply/);
const page = await fs.readFile('server/public/index.html', 'utf8');
assert.doesNotMatch(page, /id="background"|id="working-what"/);
assert.doesNotMatch(source, /refreshBackground|setActivity/);
console.log('PASS separate final reply, collapsed progress, top message controls and simplified activity');

const css = await fs.readFile('server/public/styles.css', 'utf8');
const userStyle = css.match(/\.turn\.user \.user-message \{([^}]+)\}/)[1];
const assistantStyle = css.match(/\.turn\.assistant \.body \{([^}]+)\}/)[1];
assert.doesNotMatch(assistantStyle, /background:|border:|padding:/);
assert.doesNotMatch(userStyle, /background:|border:|padding:/);
for (const style of [userStyle, assistantStyle]) assert.match(style, /overflow-wrap: anywhere/);
console.log('PASS plain user messages and unchanged plain assistant replies with long-text wrapping');

assert.match(html, /class="user-message"/);
assert.doesNotMatch(html, /class="bubble"/);
