import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import { githubCommitUrl } from '../src/core/git.js';
const sha = 'a'.repeat(40);
const url = githubCommitUrl('git@github.com:owner/project.git', sha);
assert.equal(url, 'https://github.com/owner/project/commit/' + sha);
assert.equal(githubCommitUrl('https://github.com/owner/project.git', sha), url);
assert.equal(githubCommitUrl('https://example.com/owner/project', sha), null);
assert.equal(githubCommitUrl('https://github.com/owner/project', '"><script>'), null);
const source = await fs.readFile('server/public/app.js', 'utf8');
const context = { esc: String, render: String, compact: String, clock: () => 'Sep 17, 2026, 10:40 PM', copyTexts: new Map(), toolBlock: () => '' };
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function activityChip('), source.indexOf('function drawTranscript(')), context);
const turn = { user: { id: 'u', text: 'request', turnNumber: 6 }, texts: [], steps: [], notes: [{ commitUrl: url, sha }], files: [] };
const html = context.turnHtml(turn, 0, false, 6, true);
const header = html.slice(html.indexOf('<div class="who">'), html.indexOf('id="fold-u-input"'));
assert.match(header, /6<\/span> you/);
assert.ok(header.includes('href="' + url + '"'));
assert.match(header, /target="_blank" rel="noopener noreferrer"/);
assert.equal(context.turnCommitLink({ notes: [{ sha }] }), '');
assert.equal(context.turnCommitLink({ notes: [{ commitUrl: 'javascript:alert(1)' }] }), '');
assert.equal(context.turnCommitLink({ notes: [] }), '');
console.log('PASS published GitHub commit links in turn headers; no links for missing or unsafe URLs');
