import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { viewerAddress } from '../src/core/cluster/viewers.js';
import { createCluster } from '../src/core/cluster/index.js';
const request = (address, headers = {}) => ({ socket: { remoteAddress: address }, headers });
assert.equal(viewerAddress(request('127.0.0.1')), '');
assert.equal(viewerAddress(request('::1')), '');
assert.equal(viewerAddress(request('127.0.0.1', { 'x-forwarded-for': '100.90.80.70' })), '');
assert.equal(viewerAddress(request('127.0.0.1', { 'tailscale-user-login': 'test', 'x-forwarded-for': '100.90.80.70' })), '100.90.80.70');
assert.equal(viewerAddress(request('192.168.1.2', { 'tailscale-user-login': 'test', 'x-forwarded-for': '100.90.80.70' })), '');
assert.equal(viewerAddress(request('::ffff:100.90.80.70')), '100.90.80.70');
assert.equal(viewerAddress(request('fd7a:115c:a1e0::123')), 'fd7a:115c:a1e0::123');
const root = await fs.mkdtemp(path.join(os.tmpdir(), 'viewers-'));
let cluster;
try {
  cluster = await createCluster(root);
  cluster.replica.start();
  await cluster.command({ type: 'viewer', value: { id: 'legacy', name: 'Computer browser', lastSeen: Date.now() } });
  assert.equal(cluster.status().viewers.length, 0, 'old metadata is hidden immediately');
  const local = await cluster.viewer({}, 'Mac');
  assert.ok(local.ticket, 'localhost retains browser failover credentials');
  assert.deepEqual(cluster.replica.state.viewers, {}, 'heartbeat resets old metadata');
  await cluster.viewer({ id: 'browser-one' }, 'iPhone', '100.90.80.70');
  await cluster.viewer({ id: 'browser-two' }, 'iPhone', '100.90.80.70');
  assert.equal(cluster.status().viewers.length, 1, 'same phone deduplicates across browsers');
  assert.equal(cluster.status().viewers[0].name, 'Phone');
  const id = cluster.status().viewers[0].id;
  await cluster.command({ type: 'viewer', value: { ...cluster.replica.state.viewers[id], lastSeen: Date.now() - 60000 } });
  assert.equal(cluster.status().viewers.length, 0, 'disconnected viewers disappear');
  await cluster.viewer({}, 'Mac');
  assert.deepEqual(cluster.replica.state.viewers, {}, 'expired metadata is pruned');
  const source = await fs.readFile('server/public/app.js', 'utf8');
  const row = source.split('\n').find(line => line.includes("$('viewer-list').innerHTML"));
  assert.match(row, /Connected via Tailscale/);
  assert.doesNotMatch(row, /First seen|last activity|disconnected/);
  console.log('PASS local exclusion, trusted tailnet identity, deduplication, metadata reset and compact viewer display');
} finally {
  cluster?.replica.stop();
  await fs.rm(root, { recursive: true, force: true });
}
